Repository healthcare-it-solutions/picos, pull requests merged in 2023-10, with the labels that each got.

#193 Hotfix/patientlist update
  lib/screens/study_nurse_screen/catalog_of_items_screen/pages/movement_data_page.dart
  lib/screens/study_nurse_screen/menu_screen/patients_list_card.dart
Labels: bug

#192 Change switches in patient profile to be grayed out
  lib/screens/study_nurse_screen/configuration_screen/configuration_pages.dart
  lib/screens/study_nurse_screen/configuration_screen/pages/configuration_activity_and_rest.dart
  lib/screens/study_nurse_screen/configuration_screen/pages/configuration_body_and_mind.dart
  lib/screens/study_nurse_screen/configuration_screen/pages/configuration_medication_and_therapy.dart
  lib/screens/study_nurse_screen/configuration_screen/pages/configuration_vital_values.dart
Labels: enhancement

#199 Add save-button to last screen
  lib/screens/study_nurse_screen/configuration_screen/configuration_pages.dart
Labels: bug

#202 Feature/handbook
  lib/l10n/app_de.arb
  lib/l10n/app_en.arb
  lib/screens/home_screen/overview/widgets/contact_section.dart
  pubspec.yaml
Labels: enhancement

#204 4 untranslated messages
  lib/l10n/app_de.arb
Labels: bug

#205 After creating a new patient
  lib/screens/study_nurse_screen/menu_screen/patients_list_card.dart
Labels: bug

#206 Upgrader added
  lib/screens/login_screen.dart
  pubspec.yaml
Labels: enhancement

#215 Bugfix: upgrader is currently not for web-app
  lib/screens/login_screen.dart
Labels: bug

#213 Feature/no entry push notification
  .gitignore
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/kotlin/com/example/picos/MainActivity.kt
  android/build.gradle
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  ios/Runner/Info.plist
  ios/Runner/Runner.entitlements
  lib/api/firebase_api.dart
  lib/main.dart
  pubspec.yaml
Labels: enhancement

#212 Delete unused methode
  lib/api/backend_patients_list_api.dart
Labels: change
